### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by noopkat** [george-hawkins/avrdude-conf#1]
I just wanted to say thank you so very much for making this.
True lifesaver.
😊

**Comment by george-hawkins** [comment]
Would be intrigued to know what you're doing with avrdude-conf? I'd assumed it was of extremely limited interest to most of the world :smile:

**Comment by george-hawkins** [comment]
Ah - I see your avrgirl projects. They look cool :smile:

**Comment by noopkat** [comment]
yes! I see you found them. I'm translating the conf for chips into a more workable format for use with avrgirl. A bit of simplifying, etc. You're right, in general these configuration sets are of limited interest to the rest of the world hahaha. Doesn't take away from how great it's been having the API you made. I doubt many people will end up using avrgirl, but it will be useful to have around for my own use.

**Comment by george-hawkins** [comment]
I guess you've already seen my project that builds on avrdude-conf?

It uses the Electric Imp to do the programming - so you can reprogram your AVRs wirelessly :smile:

Some of the logic might be useful to you - though it looks like you're far enough along with avrgirl that you know everything covered by my programmer logic already.

If you're interested you can see a blog entry about the project here - http://depletionregion.blogspot.ch/2014/07/imp-powered-in-system-programmer.html

The thing comes with a web and REST API - you can see the web interface here https://github.com/george-hawkins/electric-imp/tree/master/in-system-programmer

You can just see how it look (for anything to actually work the interface has to be served via an Imp).

The REST API is covered towards the end of the blog post.

The main repo for the project is http://george-hawkins.github.io/electric-imp/in-system-programmer/

All the code is in [Squirrel](http://squirrel-lang.org/) the language used by the Imp - but Squirrel is pretty easy to follow even if you don't know it.

Hope you find something useful to do with your tool - I spent ages on mine and then never did anything with it once finished :smile:
